package material.request;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;  
import java.util.Date;  
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import java.awt.*;
import java.awt.TrayIcon.MessageType;
import java.awt.event.KeyEvent;



/**
 *
 * @author Filipe Brito
 */
public class Admin extends javax.swing.JFrame {

    
   Connection conn = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   DefaultTableModel model = new DefaultTableModel();
   
   
    /**
     * Creates new form LQ_Request
     */
    public Admin() {
        initComponents();
        
        Object col[] = {"ID","Material","Date"};
        
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        conn = Admin.ConnectDB();
        
        updateTable();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
public static Connection ConnectDB(){
    try
    {
       Class.forName("org.sqlite.JDBC");
       Connection conn = DriverManager.getConnection("jdbc:sqlite:Material_Request_DB.db");
       return conn;
       
    }
        
    catch(Exception e)
    {
            JOptionPane.showMessageDialog(null, e);
            return null;
            }
}




public void updateTable(){
        Timer timer = new Timer();
            int begin = 0;
            int timeInterval = 60000;
            timer.scheduleAtFixedRate(new TimerTask() {
                @Override
    public void run() {
           
    int rowscountbefore = jTable1.getRowCount();
    jLabel4.setText(String.valueOf(rowscountbefore));
    DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
    mod.setRowCount(0);
    
      
    
    
    
    conn = Admin.ConnectDB();
    if (conn !=null)
    {
        String sql ="SELECT ID, material, date, satisfied, dateofsupply FROM material WHERE pleased IS NULL";
            
try
    {
       pst = conn.prepareStatement(sql);
       rs = pst.executeQuery();
       Object[] columnData = new Object[5];
       
       while (rs.next()){
          
          columnData[0] = rs.getString("ID");
          columnData[1] = rs.getString("material");
          columnData[2] = rs.getString("date");
          columnData[3] = rs.getString("satisfied");
          columnData[4] = rs.getString("dateofsupply");
          
          model.addRow(columnData);
                  
       }
       
    }
        
    catch(Exception e)
    {
            JOptionPane.showMessageDialog(null, e);
            
            } 
            }
            
    
           
           
    
    
    
    int rowscountafter = jTable1.getRowCount();
   if (rowscountafter > rowscountbefore) {
        try{
    //Obtain only one instance of the SystemTray object
    SystemTray tray = SystemTray.getSystemTray();

    // If you want to create an icon in the system tray to preview
    Image image = Toolkit.getDefaultToolkit().createImage("some-icon.png");
    //Alternative (if the icon is on the classpath):
    //Image image = Toolkit.getDefaultToolkit().createImage(getClass().getResource("icon.png"));

    TrayIcon trayIcon = new TrayIcon(image, "Java AWT Tray Demo");
    //Let the system resize the image if needed
    trayIcon.setImageAutoSize(true);
    //Set tooltip text for the tray icon
    trayIcon.setToolTip("System tray icon demo");
    tray.add(trayIcon);

    // Display info notification:
    trayIcon.displayMessage("Requisição de Matéria-Prima", "Novo(s) Pedido(s)!", MessageType.INFO);
    // Error:
    // trayIcon.displayMessage("Hello, World", "Java Notification Demo", MessageType.ERROR);
    // Warning:
    // trayIcon.displayMessage("Hello, World", "Java Notification Demo", MessageType.WARNING);
}catch(Exception ex){
    System.err.print(ex);
}
    }
    
    
    }

    
}, begin, timeInterval);
   
   
}



    public void AddRow(){
        Date date = new Date();  
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yy HH:mm:ss");  
        String strDate = formatter.format(date);  
        
        String lastrowstr = null;
        
        DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
        mod.setRowCount(0);
        
        //get last row
        try {
        Statement st = conn.createStatement();
        String query = ("SELECT * FROM material ORDER BY Id DESC LIMIT 1;");
         rs = st.executeQuery(query);
         if (rs.next()) {
           int lastrow = rs.getInt("ID") + 1;
           
           lastrowstr = String.valueOf(lastrow); 
           
           
           
         }
         
        }catch (Exception e) {
         e.printStackTrace();
        }
        
    
        
        
        String sql ="INSERT INTO material(ID, material, date, pleased, dateofsupply)VALUES(?,?,?,?,?)";
            
       
        
    
try
    {
       pst = conn.prepareStatement(sql);
       
       
          
          pst.setString(1, lastrowstr);
          pst.setString(2, jtxtMissing.getText());
          pst.setString(3, strDate);
          
          
          
          
          
        
          
          
         
          pst.execute();
          JOptionPane.showMessageDialog(null, "SystemUpdated");
          rs.close();
          pst.close();
          
          
          
       }
    
        
    catch(HeadlessException | SQLException e)
    {
            JOptionPane.showMessageDialog(null, e);
            
            }

            
            updateTable();
            DefaultTableModel iModel = (DefaultTableModel) jTable1.getModel();
            if (jTable1.getSelectedRow() == -1){
                if (jTable1.getRowCount() == 0){
                    JOptionPane.showMessageDialog(null, "Data Entry Update confirmed", "Data Entry System", JOptionPane.OK_OPTION);
                    
                }
            }
    }

               
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtMissing = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jtxtSupply = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MateriaPrima", "Data", "Satisfeito", "Data/HoraAbastecimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 780, 220));

        jLabel1.setText("LQ em falta:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jtxtMissing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMissingActionPerformed(evt);
            }
        });
        jtxtMissing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtMissingKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtMissing, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 160, 30));

        jButton1.setText("Pedir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jtxtSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSupplyActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 160, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("LQ Abastecido:");

        jButton2.setText("Abastecer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 380, 110));

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jButton4.setText("Ver Histórico");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtMissingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMissingActionPerformed
         
    }//GEN-LAST:event_jtxtMissingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddRow();
                    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSupplyActionPerformed
        
    }//GEN-LAST:event_jtxtSupplyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            if (jTable1.getSelectedRow() == -1){
                if (jTable1.getRowCount() == 0){
                    JOptionPane.showMessageDialog(null, "No data to delete", "Data Entry Form", JOptionPane.OK_OPTION);
                }else{
                    JOptionPane.showMessageDialog(null, "Select a row to delete ", "Data Entry Form", JOptionPane.OK_OPTION);
                }
            }else{
                
                int row = jTable1.getSelectedRow();

    String ID = model.getValueAt(row, 0).toString();
    
    
    
                
                Date date = new Date();  
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yy HH:mm:ss");  
        String strDate = formatter.format(date);  
        
        
        DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
        mod.setRowCount(0);
        
        
        
        
        try {
            Statement st = conn.createStatement();
            String sql1 ="UPDATE material SET pleased=? WHERE ID=?";
        pst = conn.prepareStatement(sql1);
        pst.setString(1, "X");
        pst.setString(2, ID);
        
        pst.execute();
          JOptionPane.showMessageDialog(null, "SystemUpdated");
          rs.close();
          pst.close();
        
         
        
        }catch(HeadlessException | SQLException e)
    {
            JOptionPane.showMessageDialog(null, e);
            
            }
            updateTable();
            DefaultTableModel iModel = (DefaultTableModel) jTable1.getModel();
            if (jTable1.getSelectedRow() == -1){
                if (jTable1.getRowCount() == 0){
                    JOptionPane.showMessageDialog(null, "Data Entry Update confirmed", "Data Entry System", JOptionPane.OK_OPTION);
                    
                }
            }        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new History().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtxtMissingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMissingKeyPressed
   if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            AddRow();
            
            
        }
    }//GEN-LAST:event_jtxtMissingKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Admin().setVisible(true);
                
                
            
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtMissing;
    private javax.swing.JTextField jtxtSupply;
    // End of variables declaration//GEN-END:variables

    

    

    
}
